project/karma/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('base/',views.base,name='base'),
    path('',views.index,name='home'),
    path('blog/',views.blog,name='blog'),
    path('profile/', views.profile, name="profile"),
    path('profile/update', views.update_profile, name="update_profile"),
    path('cart/',views.cart,name='cart'),
    path('cart/add/',views.add_to_cart,name='add_to_cart'),
    path('cart/update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('cart/delete/<int:item_id>/', views.delete_cart, name='delete_cart'),
    path('category_detail/',views.category_detail,name='category_detail'),
    path('checkout/',views.checkout,name='checkout'),
    path('confirmation/',views.confirmation,name='confirmation'),
    path('contact/',views.contact,name='contact'),
    path('elements/',views.elements,name='elements'),
    path('single-blog/',views.single_blog,name='single_blog'),
    path('product/<slug:slug>/',views.product_detail,name='product_detail_url'),
    path('tracking/',views.tracking,name='tracking'),
    path('register/',views.register,name='register'),
    path('order/', views.order, name="order"),
    path('orders/', views.orders, name="orders"),  # hamma zakazlar adminga
    path('orders/<int:order_id>/change-status/', views.change_status, name="change_status"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('karma.urls')),
    path('accaunts/', include('django.contrib.auth.urls'))
]+ static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +static(settings.STATIC_URL, documet_root=settings.STATIC_ROOT) 

project/karma/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
# Create your models here.
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)

# ======================= CATEGORY ============================


class Category(models.Model):
    title = models.CharField('Sarlavha', db_index=True, max_length=255)
    slug = models.SlugField('manzil', unique=True)
    date = models.DateTimeField('Vaqt', default=timezone.now)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug': self.slug})


class Brend(models.Model):
    title = models.CharField('Sarlavha', db_index=True, max_length=255)
    slug = models.SlugField('manzil', unique=True)
    date = models.DateTimeField('Vaqt', default=timezone.now)

    class Meta:
        verbose_name = 'Brend'
        verbose_name_plural = 'Brendlar'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('brend_detail_url', kwargs={'slug': self.slug})


class Product(models.Model):
    title = models.CharField('Sarlavha', max_length=255, db_index=True)
    popular = models.IntegerField('ko`rilganlar soni', default=0)
    image_1 = models.ImageField('Rasm 1')
    image_2 = models.ImageField('Rasm 2')
    image_3 = models.ImageField('Rasm 3')
    text = models.TextField('Taxt')
    slug = models.SlugField('Manzil', unique=True)
    price = models.IntegerField('Narx', default=0)
    date = models.DateTimeField('Vaqt', default=timezone.now)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, related_name='category_set')
    brend = models.ForeignKey(
        Brend, related_name='brend_set', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title

    def discount(self):
        return self.price + (self.price // 10)

    
    def get_absolute_url(self):
        return reverse('product_detail_url', kwargs={'slug': self.slug})

# ========================= CART ==============================


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)
    price = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username


class OrderStatus(models.Model):
    name = models.CharField(max_length=255)
    system_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class PaymentType(models.Model):
    name = models.CharField(max_length=255)
    system_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='OrderProduct')
    total = models.IntegerField(default=0)
    order_status = models.ForeignKey(OrderStatus, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    payment_type = models.ForeignKey(PaymentType, on_delete=models.PROTECT)


class Orderproduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    count = models.IntegerField(default=1)
    product_price = models.IntegerField(default=0)
    product_name = models.CharField(max_length=255)

    def summ(self):
        return self.product_price * self.count

    def __str__(self):
        return self.user

project/karma/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Username',required=True,widget=forms.TextInput(attrs={'class' : 'form-control footr-input margin-b-20','placeholder':'Username'}))
    password1 = forms.CharField(label = "Parol", required=True,widget=forms.PasswordInput(attrs={'class' : 'form-control footer-input margin-b-20','placeholder':'Parol'}))

    password2 = forms.CharField(label="Takroriy parol",required=True,widget=forms.PasswordInput(attrs={'class' : 'form-control footer_input margin-b-20','placeholder':'Takroriy parol'}))

    email = forms.EmailField(label = "Email", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20','placeholder':'Email'}))

    first_name = forms.CharField(label = "Ism", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20','placeholder':'Ism'}))

    last_name = forms.CharField(label = "Familiya", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20','placeholder':'Familiya'}))

    class Meta:
        model = User
        fields = ("first_name","last_name",  "email", "username", "password1", "password2", )

    def save(self,commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]

        if commit:
            user.save()
        return user

project/karma/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .models import *
from django.db.models import Sum,F
from django.http import Http404,HttpResponseRedirect,HttpResponse

# Create your views here.


def base(request):
    return render(request, 'karma/base.html')


def index(request):
    last_product = Product.objects.order_by('-date')[:8]
    best_product = Product.objects.filter(popular__gte = 1000)[:8]
    context = {
        'last_product': last_product,
        'best_product': best_product
    }
    return render(request, 'karma/index.html', context)

def blog(request):
    return render(request, 'karma/blog.html')


def category_detail(request):
    return render(request, 'karma/category_detail.html')

def checkout(request):
    return render(request, 'karma/checkout.html')

def confirmation(request):
    return render(request, 'karma/confirmation.html')

def contact(request):
    return render(request, 'karma/contact.html')

def elements(request):
    return render(request, 'karma/elements.html')

def single_blog(request):
    return render(request, 'karma/single-blog.html')


def tracking(request):
    return render(request, 'karma/tracking.html')


# Profile


def profile(request):
    return render(request, 'karma/profile.html')


def update_profile(request):
    if request.user.is_authenticated:
        profile, created = Profile.objects.get_or_create(user=request.user)
        if request.method == 'POST':
            profile = request.user.profile
            profile.phone = request.POST.get('phone')
            profile.address = request.POST.get('address')
            profile.save()
        return redirect('profile')
    return redirect('home')


#  Register =============


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            profile = Profile()
            profile.user = request.user
            profile.save()
            # log the user in
            return redirect('home')
    else:
        form = RegisterForm()
    return render(request, 'karma/register.html', {'form': form})

def product_detail(request, slug):
    product_detail = Product.objects.get(slug=slug)
    product_detail.popular += 1
    product_detail.save()
    context = {
        'product_detail': product_detail

    }
    return render(request, 'karma/single-product.html', context)


#  Add to Cart
def add_to_cart(request):
    product_slug = request.GET.get("id")
    product = Product.objects.get(id=product_slug)
    if request.user.is_authenticated:
        if request.method == 'GET':
            if not request.user.cartitem_set.filter(product=product).exists():
                item = CartItem()
                item.product = product
                item.user = request.user
                item.count = request.GET.get('qty')
                item.save()
            else:
                item = request.user.cartitem_set.get(product=product)
                item.count += int(request.GET.get('qty'))
                item.save()
                print(item)
            return HttpResponse('Done')
        return HttpResponse('Unexpected method')
    return HttpResponse('Authenticated user is null')



def cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_amount = CartItem.objects.annotate(
        item_price=F("count")* F("product__price")
    ).aggregate(Sum("item_price")).get("item_price__sum",0)

    context = {
        'cart_items':cart_items,
        'total_amount':total_amount

    }
    return render(request,'karma/cart.html',context)

def update_cart(request,item_id):
    item = CartItem.objects.get(id=item_id)
    if request.user.is_authenticated:
        if request.method == 'POST':
            item.count = request.POST.get('count')
            item.save()
            if int(item.count) < 1 :
                item.delete()
            return redirect('cart')
        return HttpResponse('Unexpected method')
    return HttpResponse('Authenticated user is null')




def delete_cart(request, item_id):
    item = CartItem.objects.get(id=item_id)
    if request.user.is_authenticated:
        if request.method == 'POST':
            item.delete()
            return redirect('cart')
        return HttpResponse('Unexpected method')
    return HttpResponse('Authenticated user is null')


def order(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            order = Order()
            order.user = request.user
            order.order_status = OrderStatus.objects.get(system_name__exact='new')
            order.payment_type = PaymentType.objects.get(system_name__exact=request.POST.get('payment_type'))
            order.save()
            items = CartItem.objects.filter(user=request.user)

            for item in items:
                order_product = Orderproduct()
                order_product.order = order
                order_product.product = item.product
                order_product.count = item.count
                order_product.product_price = item.product.price
                order_product.product_name = item.product.title
                order_product.save()
            if order.payment_type.system_name == 'payme':
                pass
            return redirect('cart')
        return HttpResponse('Unexpected method')
    return HttpResponse('Authenticated user is null')

# Orders =================

def orders(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:

            orders = Order.objects.order_by('-date')
            order_statuses = OrderStatus.objects.all()
            return render(request, 'karma/orders.html', {'orders': orders, 'order_statuses': order_statuses})
    return redirect('home')

    
def change_status(request, order_id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            order = Order.objects.get(id=order_id)
            order.order_status = OrderStatus.objects.get(id=request.POST.get('order_status'))
            order.save()
            return redirect('orders')
    return redirect('home')

project/karma/templates/karma/cart.html
{% extends 'karma/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
<link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}" />
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.skinFlat.css' %}" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Shopping Cart</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Cart</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive" style="height:auto ;">
                <table class="table "  style="height:auto ;">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col"></th>
                            <th scope="col">Quantity and Update</th>

                            <th scope="col">Price</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                        <tr>

                            <td>
                                <div class="media">
                                    <div class="d-flex">
                                        <img style="width: 151px;height: 102px;" src="{{item.product.image_1.url}}"
                                            alt="">
                                    </div>
                                    <div class="media-body">
                                        <p>{{item.product.title}}</p>
                                    </div>
                                </div>
                            </td>

                            <td>
                                <h5></h5>
                            </td>
                            <td>
                                <form class="product_count" method="POST" action="{% url 'update_cart' item.id %}">

                                    {% csrf_token %}



                                    <input type="text" name="count" maxlength="12" id="count_{{ item.id }}"
                                        value="{{ item.count }}" title="Quantity:" class="input-text qty">
                                    <button
                                        onclick="var result = document.getElementById('count_{{ item.id }}'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                                        class="increase items-count" type="button"><i
                                            class="lnr lnr-chevron-up"></i></button>
                                    <button
                                        onclick="var result = document.getElementById('count_{{ item.id }}'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                                        class="reduced items-count" type="button"><i
                                            class="lnr lnr-chevron-down"></i></button>

                                    <button style="border-radius:10px 
                                            ;" type="submit" class="update-cart"
                                        data-item-id="{{ item.id }}">Yangilash</button>
                                </form>
                            </td>

                            <td>
                                <h5>${{item.product.price}}.00</h5>
                            </td>
                            <td>
                                <form id="delete-form" method="post" action="{% url 'delete_cart' item.id %}">
                                    {% csrf_token %}
                                    <!-- <input type="submit" value="Savatchadan olib tashlash"> -->
                                    <button style="border-radius: 10px;" class="delete-cart"
                                        data-item-id="{{ item.id }}">
                                        <i class="lnr lnr-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}

                        <tr class="bottom_button">
                            <td class="d-flex justify-content-between align-items-center">
                                <p>
                                    TOTAL : 
                                  
                                </p>
                                <h5 class="text-center">  ${{total_amount}}.00</h5>
                            </td>
                      
                            <td>
                              
                            </td>
                            <!-- ======= DELETE CART ====== -->
                            <td colspan="3">
                                <form action="{% url 'order' %}" method="POST" class="d-flex justify-content-between align-items-center"> 
                                    {% csrf_token %}
                                    <label for="payment_type">Payment Type:</label>
                                    <select name="payment_type" system_name="payment_type" id="payment_type">
                                        <option value="payme">Payme</option>
                                        <option value="cash">Naxd</option>
                                        <!-- Add other payment types if necessary -->
                                    </select>
                                    <button class="btn primary-btn" type="submit">To'lov qilish</button>
                                </form> 
                                
                            </td> 
                                <!-- ==== END === -->

                             
                        </tr>



                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->


<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
    integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
    crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static 'js/gmaps.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% endblock %}

project/karma/templates/karma/contact.html
{% extends 'karma/base.html' %}
{% load static %}
{% block content %}


<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
<link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}" />
<link rel="stylesheet" href="{% static 'css/ion.rangeSlider.skinFlat.css' %}" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Contact Us</h1>
                <nav class="d-flex align-items-center">
                    <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="category.html">Contact</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Contact Area =================-->
<section class="contact_area section_gap_bottom">
    <div class="container">
        <div id="mapBox" class="mapBox" data-lat="40.701083" data-lon="-74.1522848" data-zoom="13"
            data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia." data-mlat="40.701083"
            data-mlon="-74.1522848">
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="contact_info">
                    <div class="info_item">
                        <i class="lnr lnr-home"></i>
                        <h6>California, United States</h6>
                        <p>Santa monica bullevard</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-phone-handset"></i>
                        <h6><a href="#">00 (440) 9865 562</a></h6>
                        <p>Mon to Fri 9am to 6 pm</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope"></i>
                        <h6><a href="#">support@colorlib.com</a></h6>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <form class="row contact_form" action="contact_process.php" method="post" id="contactForm"
                    novalidate="novalidate">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name"
                                placeholder="Enter your name" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Enter your name'">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email"
                                placeholder="Enter email address" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Enter email address'">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" name="subject"
                                placeholder="Enter Subject" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Enter Subject'">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control" name="message" id="message" rows="1"
                                placeholder="Enter Message" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Enter Message'"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="primary-btn">Send Message</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>



<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
    integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
    crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static 'js/gmaps.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

project/karma/templates/karma/orders.html
{% extends 'karma/base.html' %}

{% load static %}

{% block content %}

<div style="width: 1130px; margin: 10px auto;height: 1000px;margin-top: 500px;">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Date</th>
                <th>Customer Name</th>
                <th>Customer Phone</th>
                <th>Customer Address</th>
                <th>Order Status</th>
                <th>Payment Type</th>
                <th>Products</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr >
                <td>{{order.id}}</td>
                <td>{{order.date}}</td>
                <td>{{order.user.username}} </td>
                <td>{{order.user.phone}}</td>
                <td>{{order.user.address}}</td>
                <td>
                    <form action="{% url 'change_status' order.id %}" method="POST">
                        {% csrf_token %}
                        <select onchange="{this.form.submit()}" name="order_status">
                            {% for status in order_statuses %}
                            <option value="{{status.id}}" {% if order.order_status.id == status.id %}selected{% endif %}>{{status.name}}</option>
                            {% endfor %}
                        </select>
                    </form>
                </td>
                <td>{{order.payment_type.name}}</td>
                <td>
                    {% for product in order.orderproduct_set.all %}
                    {{product.product_name}} | {{product.product_price}} * {{product.count}} -> {{product.summ}}
                    <hr>
                    {% endfor %}
                </td>
                <td>{{order.total}}</td>
                <style>
                    .order-status-color{
                       {% if order.order_status.system_name == 'new' %}
                       background-color: blue !important;
                       color: white !important;
                       {% elif order.order_status.system_name == 'process' %}
                       background-color: #777700 !important;
                       color: white !important;
                       {% elif order.order_status.system_name == 'done' %}
                       background-color: green !important;
                       color: white !important;
                       {% elif order.order_status.system_name == 'payed' %}
                       background-color: gray !important;
                       color: black !important;
                       {% endif %}
                    }
               </style>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

project/karma/templates/karma/profile.html
<style>
    form{
        padding: 4% 6%;
    }
</style>



<form action="{% url 'update_profile' %}" method="POST">
    {% csrf_token %}
    <p>
        <label for="">Phone</label>
        <input type="text" value="{% if user.profile.phone != null %}{{user.profile.phone}}{% endif %}" name="phone">
    </p>
    <p>
        <label for="">Address</label>
        <input type="text" value="{% if user.profile.address != null %}{{user.profile.address}}{% endif %}" name="address">
    </p>
    <p>
        <button>Send</button>
    </p>
</form>